const quotes = [
    { author: "Bill Gates", quote: "It's fine to celebrate success, but it is more important to heed the lessons of failure." },
    { author: "Steve Jobs", quote: "I’m convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance." },
    { author: "Elon Musk", quote: "When something is important enough, you do it even if the odds are not in your favor." },
    { author: "Albert Einstein", quote: "In the middle of difficulty lies opportunity." },
    { author: "Thomas Edison", quote: "I have not failed. I've just found 10,000 ways that won't work." },
    { author: "Grace Hopper", quote: "The most dangerous phrase in the language is, 'We've always done it this way.'" },
    { author: "James Clear", quote: "You do not rise to the level of your goals. You fall to the level of your systems." },
    { author: "Mark Zuckerberg", quote: "The biggest risk is not taking any risk." },
    { author: "Linus Torvalds", quote: "Talk is cheap. Show me the code." },
    { author: "Richard Branson", quote: "Do not be embarrassed by your failures, learn from them and start again." },
    { author: "Albert Einstein", quote: "Anyone who has never made a mistake has never tried anything new." },
    { author: "Michael Jordan", quote: "I've failed over and over and over again in my life and that is why I succeed." },
    { author: "Walt Disney", quote: "All our dreams can come true, if we have the courage to pursue them." },
    { author: "Seth Godin", quote: "You don’t have to be the best in the world. You just have to be the best in the room." },
    { author: "Ralph Waldo Emerson", quote: "Our greatest glory is not in never failing, but in rising every time we fail." },
    { author: "John Wooden", quote: "Success is never final, failure is never fatal. It's courage that counts." },
    { author: "Yoda", quote: "The greatest teacher, failure is." },
    { author: "J.K. Rowling", quote: "It is impossible to live without failing at something unless you live so cautiously that you might as well not have lived at all." },
    { author: "Tim Berners-Lee", quote: "We need diversity of thought in the world to face the new challenges." },
    { author: "Robert F. Kennedy", quote: "Only those who dare to fail greatly can ever achieve greatly." },
    { author: "Nelson Mandela", quote: "Do not judge me by my successes, judge me by how many times I fell down and got back up again." },
    { author: "Bruce Lee", quote: "Mistakes are always forgivable if one has the courage to admit them." },
    { author: "Mark Zuckerberg", quote: "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough." },
    { author: "Reed Hastings", quote: "Do not tolerate brilliant jerks. The cost to teamwork is too high." },
    { author: "Henry Ford", quote: "Failure is simply the opportunity to begin again, this time more intelligently." },
    { author: "Steve Wozniak", quote: "The best ideas start as conversations." },
    { author: "Terry Pratchett", quote: "Sometimes it’s better to light a flamethrower than curse the darkness." },
    { author: "Jeff Bezos", quote: "If you double the number of experiments you do per year, you're going to double your inventiveness." },
    { author: "Nikola Tesla", quote: "The present is theirs; the future, for which I really worked, is mine." },
    { author: "Eric Raymond", quote: "Good programmers know what to write. Great ones know what to rewrite (and reuse)." },
    { author: "Tony Robbins", quote: "Setting goals is the first step in turning the invisible into the visible." },
    { author: "Bill Gates", quote: "Don't compare yourself with anyone in this world. If you do so, you are insulting yourself." },
    { author: "Marissa Mayer", quote: "I always did something I was a little not ready to do. I think that’s how you grow." },
    { author: "David Heinemeier Hansson", quote: "You should rarely make the same mistake twice." },
    { author: "Larry Page", quote: "Always deliver more than expected." },
    { author: "Robert C. Martin", quote: "Truth can only be found in one place: the code." },
    { author: "Sheryl Sandberg", quote: "Done is better than perfect." },
    { author: "Reid Hoffman", quote: "If you are not embarrassed by the first version of your product, you’ve launched too late." },
    { author: "Albert Einstein", quote: "Strive not to be a success, but rather to be of value." },
    { author: "Steve Jobs", quote: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." },
    { author: "Cory House", quote: "Code is like humor. When you have to explain it, it’s bad." },
    { author: "Isaac Asimov", quote: "Self-education is, I firmly believe, the only kind of education there is." },
    { author: "Brian Tracy", quote: "The key to success is to focus our conscious mind on things we desire, not things we fear." },
    { author: "Harvey Specter", quote: "Winners don't make excuses when the other side plays the game." },
    { author: "Vince Lombardi", quote: "Perfection is not attainable, but if we chase perfection, we can catch excellence." },
    { author: "Zig Ziglar", quote: "People often say that motivation doesn't last. Well, neither does bathing – that's why we recommend it daily." },
    { author: "Robert T. Kiyosaki", quote: "The richest people in the world look for and build networks, everyone else looks for work." },
    { author: "James Clear", quote: "Success is the product of daily habits—not once-in-a-lifetime transformations." },
    { author: "Dale Carnegie", quote: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success." },
    { author: "Steve Jobs", quote: "Stay hungry, stay foolish." },
    { author: "Tony Robbins", quote: "It's not what we do once in a while that shapes our lives, it's what we do consistently." },
    { author: "Malcolm Gladwell", quote: "Practice isn't the thing you do once you're good. It's the thing you do that makes you good." },
    { author: "John Wooden", quote: "Things turn out best for the people who make the best of the way things turn out." },
    { author: "Benjamin Franklin", quote: "Tell me and I forget. Teach me and I remember. Involve me and I learn." },
    { author: "Bill Gates", quote: "If you are born poor it’s not your mistake, but if you die poor it’s your mistake." },
    { author: "Derek Sivers", quote: "If information was the answer, we’d all be billionaires with perfect abs." },
    { author: "Reid Hoffman", quote: "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down." },
    { author: "Coco Chanel", quote: "Success is most often achieved by those who don't know that failure is inevitable." },
    { author: "Henry Ford", quote: "Whether you think you can, or you think you can’t – you’re right." },
    { author: "Charles Darwin", quote: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change." },
    { author: "Bruce Lee", quote: "Knowing is not enough; we must apply. Willing is not enough; we must do." },
    { author: "Marie Curie", quote: "Be less curious about people and more curious about ideas." },
    { author: "John Carmack", quote: "Focused, hard work is the real key to success." },
    { author: "Thomas Jefferson", quote: "I'm a great believer in luck, and I find the harder I work the more I have of it." },
    { author: "Naval Ravikant", quote: "Escape competition through authenticity." },
    { author: "Tony Fadell", quote: "The only way you survive is you continuously transform into something else." },
    { author: "Larry Wall", quote: "The three virtues of a programmer: laziness, impatience, and hubris." },
    { author: "Plato", quote: "The beginning is the most important part of the work." },
    { author: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop." },
    { author: "Michael Dell", quote: "Ideas are a commodity. Execution of them is not." },
    { author: "Linus Torvalds", quote: "Intelligence is the ability to avoid doing work, yet getting the work done." },
    { author: "George Bernard Shaw", quote: "Progress is impossible without change, and those who cannot change their minds cannot change anything." },
    { author: "Winston Churchill", quote: "Success is not final, failure is not fatal: it is the courage to continue that counts." },
    { author: "Dr. Seuss", quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose." },
    { author: "Bill Gates", quote: "Your most unhappy customers are your greatest source of learning." },
    { author: "Sheryl Sandberg", quote: "If you're offered a seat on a rocket ship, don't ask what seat! Just get on." },
    { author: "Peter Drucker", quote: "The best way to predict the future is to create it." },
    { author: "Mark Twain", quote: "The secret of getting ahead is getting started." },
    { author: "Denis Waitley", quote: "Expect the best, plan for the worst, and prepare to be surprised." },
    { author: "Neil Gaiman", quote: "The one thing that you have that nobody else has is you. Your voice, your mind, your story, your vision." },
    { author: "Pablo Picasso", quote: "Action is the foundational key to all success." },
    { author: "Maya Angelou", quote: "You will face many defeats in life, but never let yourself be defeated." },
    { author: "Ralph Waldo Emerson", quote: "Do not go where the path may lead, go instead where there is no path and leave a trail." },
    { author: "Confucius", quote: "The man who moves a mountain begins by carrying away small stones." },
    { author: "Jim Rohn", quote: "If you are not willing to risk the unusual, you will have to settle for the ordinary." },
    { author: "Jack Canfield", quote: "Don't worry about failures, worry about the chances you miss when you don't even try." },
    { author: "Julius Caesar", quote: "Experience is the teacher of all things." },
    { author: "James Cameron", quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success." },
    { author: "Will Smith", quote: "Greatness is not this wonderful, esoteric, elusive, godlike feature that only the special among us will ever taste. It's something that truly exists in all of us." }
  ];

  export default quotes;